default_language_version:
  python: python
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
      stages: [commit]
    - id: end-of-file-fixer
      stages: [commit]
    - id: trailing-whitespace
    - id: check-json
      exclude: mathics_scanner/data/characters.json
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        stages: [commit]
        args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    - id: black
      language_version: python3
      stages: [commit]
      exclude: version.py
