name: Compile the translation tables
env:
  GITHUB_TOKEN: ${{ secrets.github_token }}
  COMMIT_MSG: Compiled the translation tables
  skip-checks: true
on: 
  push:
    branches:
      - master
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install PyYAML
        run: pip install PyYAML
      - name: Pull the repo locally
        run: git clone "https://github.com/${GITHUB_REPOSITORY}.git" .
      - name: Compile the translation tables
        run: |
          ls
          python admin-tools/compile-translation-tables.py
      - name: Commit to the repository
        run: |
          git config user.name "GitHub Actions Robot"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git checkout master
          git add .
          git commit -m "${COMMIT_MSG}"
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)

