name: Mathics_Script (Mathics doctest)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install OS dependencies
      run: |
        sudo apt-get update -qq && sudo apt-get install -qq liblapack-dev llvm-dev tesseract-ocr
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Install Mathics_Scanner
      run: |
        make
    - name: Test Mathics3
      run: |
        # Until next Mathics3/mathics-core release is out...
        git clone https://github.com/Mathics3/mathics-core.git
        cd mathics-core/
        make PIP_INSTALL_OPTS='[full]'
        # pip install Mathics3[full]
        cd ..
        MATHICS_CHARACTER_ENCODING="ASCII" make check-mathics
