# Copied from SymPy https://github.com/sympy/sympy/pull/27183

name: Mathics3 Scanner (Pyodide)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pyodide-test:
    runs-on: ubuntu-latest
    env:
      PYODIDE_VERSION: 0.28.2
      # PYTHON_VERSION and EMSCRIPTEN_VERSION are determined by PYODIDE_VERSION.
      # The appropriate versions can be found in the Pyodide repodata.json
      # "info" field, or in Makefile.envs:
      # https://github.com/pyodide/pyodide/blob/main/Makefile.envs#L2
      PYTHON_VERSION: 3.13.2
      EMSCRIPTEN_VERSION: 4.0.9
      NODE_VERSION: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          actions-cache-folder: emsdk-cache

      - name: Install pyodide-build
        run: pip install pyodide-build

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Pyodide virtual environment and run tests
        run: |
          # Set up Pyodide virtual environment
          pyodide xbuildenv install ${{ env.PYODIDE_VERSION }}
          pyodide venv .venv-pyodide

          # Activate the virtual environment
          source .venv-pyodide/bin/activate
          pip install "setuptools" PyYAML click packaging pytest

          # We should comment out after next mathics-core release
          python -m pip install --no-build-isolation --no-deps -e git+https://github.com/Mathics3/mathics-core#egg=Mathics3
          # python -m pip Mathics3

          pip install --no-build-isolation -e .

          pip install -r requirements-dev.txt
          bash ./admin-tools/make-JSON-tables.sh
          make check
